- name: Fact Dump
  hosts: all
  tasks:
    #- name: Exibindo Facts
      #debug:
        #var: ansible_facts

    - name: Executando when condition
      ansible.builtin.command: echo Debian
      when: ansible_facts['os_family'] == "RedHat"
