---
# tasks file for webserver
- name: Install Nginx
  apt: 
    name: "nginx"
    state: latest

- name: Copiando index.html
  copy:
    src: index.html
    dest: "{{ nginx_html }}"
  notify:
    - Restart nginx
