- hosts: all
  gather_facts: false
  tasks:
    - name: Instalando Apache
      yum:
        name: httpd
        state: latest
      tags:
        - initial    
- name: Setar nome
      shell: echo "<h1>Felipe Defacio</h1>" > /var/www/html/index.html
      become: True
      notify:
        - restart service
  handlers:
    - name: restart service
      service:
        name: httpd
        enabled: yes
        state: reloaded
      become: yes

